# Generated by Django 4.2.2 on 2023-07-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
    ]
