# Generated by Django 4.2.2 on 2023-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(upload_to='files/'),
        ),
    ]
