# Generated by Django 4.2.2 on 2023-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
